name: New release
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Create environment file
        run: |
          node script/setup-environment.js
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Conventional Changelog Action
        id: changelog

        uses: TriPSs/conventional-changelog-action@v5.4.0
        with:
          github-token: ${{ secrets.github_token }}
          git-user-name: LucaPascucci
          git-user-email: lucapascucci19@gmail.com
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Deploy
        run: |
          npm run deploy
